spring:
  datasource:
    url: jdbc:mysql://localhost:3306/p5home?serverTimezone=UTC
    username: root
    password: zxcvbnm
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8000

mybatis:
  mapper-locations: classpath:mapper/*

logging:
  level:
    com.dawnop.mapper: debug